version: "3.9"

services: 
    app:
      build: ./Server
      container_name: server-olc1
      ports:
      - "3000:3000"
    web: 
      build: ./Client
      container_name: client-olc1
      restart: always
      ports:
        - "8080:80"
