version: "3.9"

services: 
    app:
      build: ./Server
      container_name: server-olc1
      ports:
      - "3000:3000"
    web: 
      build: ./Client
      container_name: client-olc1
      # Always: restart the container if it stops. If it is manually stopped, 
      # it is restarted only when Docker daemon restarts or the container itself is manually restarted
      restart: unless-stopped
      ports:
        - "8080:80"
